<!-- End Page Content -->
          </td>
        </tr>
        <tr valign="bottom">
          <td align="center">
            <br><br><br>
            Site written by <a href="http://www.hinst.net"><b>Rob H</b></a> and <a href="http://www.sinisterwizard.com"><b>Rob L</b></a>.<br>
            Graphic design by <a href="http://www.ascendancestudios.com"><b>Adam M</b></a>.<br>
            MP3 Player provided by <a href="http://www.webamp.net"><b>Webamp.net</b></a>.<br><br>
	    Contact <a href="mailto:<? print $info_email; ?>"><b><? print $info_email; ?></b></a> for more information.<br><br>
            &copy; 2002 <? print $sitename; ?>, All rights reserved.<br>
            <a href="<? print $baseURL; ?>/legal.php">Legal Information</a> &bull;&nbsp;
            <a href="<? print $baseURL; ?>/tos.php">Terms of Service</a> &bull;&nbsp;
            <a href="<? print $baseURL; ?>/privacy.php">Privacy Policy</a><br>
            <br><br>
          </td>
        </tr>
      </table>
    </td>
    <td align="right" height="100%">
      <? include('templates/general/sideBar.inc'); ?>
    </td>
  </tr>
</table>
</body>
</html>
