<!-- Start QuickStats Box -->
<table width="150" border="0" cellspacing="0" cellpadding="2">
  <tr>
    <td class="menu_text" align="center">
      Currently logged in as:<br>
      <b><? print $authenticated_user; ?></b>
    </td>
  </tr>
  <tr>
    <td>
      &nbsp;
    </td>
  </tr>
  <tr>
    <td class="menu_text" align="center">
      <a class="menu_link" href="<? print $baseURL; ?>/index.php?action=logout" target="_top">Click here to log out</a>
    </td>
  </tr>
  <tr>
    <td>
      &nbsp;
    </td>
  </tr>
</table>
<!-- End QuickStats Box -->
