                      </td>
                      <td style="background-image: url('images/comments_frame_right_slat.jpg'); font-size: 0px" width="23">
                        <img src="images/spacer.gif" border="0" alt="" height="1" width="23">
                      </td>
                    </tr>
                    <tr>
                      <td colspan="3" style="background-image: url('images/comments_frame_bottom.jpg'); font-size: 0px" width="415" height="13">
                        <img src="images/spacer.gif" border="0" alt="" width="415" height="13">
                      </td>
                    </tr>
                  </table>
