<table border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td align="center">
      No Challenger<br><br><br><br>
      <img src="images/spacer.gif" width="<? print $user_icon_width; ?>" height="1" border="0" alt="">
    </td>
  </tr>
  <tr>
    <td align="center">
      [<a href="joinBattle.php?battle_id=<? print $battle_id; ?>">Click here to join this battle.</a>]
    </td>
  </tr>
</table>
