<br>
<table width="400" class="items" border="0" cellspacing="0" cellpadding="4">
  <tr>
    <td class="item_title">
      Rules:
    </td>
  </tr>
  <tr>
    <td>
      <b>Your Account</b>
    </td>
  </tr>
  <tr>
    <td>
      <ul>
        <li>Upon creation of your account, you agree to abide by all rules set forth in the User Agreement as well as this list of rules, and any other rules appearing on the website.</li>
        <li><? print $sitename; ?> reserves the right to suspend or cancel any account at any time for any reason, including but not limited to: violation of the User Agreement, violation of any of these rules, or misuse of this website.</li>
      </ul>
    </td>
  </tr>
  <tr>
    <td>
      <b>Starting and Joining Battles</b>
    </td>
  </tr>
  <tr>
    <td>
      <ul>
      	<li>You must be a registered member and currently logged on to the site in order to start or join a battle.</li> 
      	<li>Members who have not yet participated in any battles may start a battle of their own or join another user's open battle.</li>
      	<li>Members who have already participated in one or more battles must vote on <? print $vote_bank_quota; ?> separate battles before they may start or join another battle.</li>
      	<li>You may not join a battle that you started.</li>
      	<li>You may not participate in more than <? print $max_simultaneous_battles; ?> battles at one time.</li>
        <li>You may only join a battle started by a user that is the same rank as you, unless the battle is a challenge battle. Any user may challenge any other user to a battle.</li>
        <li>MP3 uploads may not exceed <? print floor($max_mp3_size / 1024); ?> kb (<? print $max_mp3_size; ?> bytes).</li>
        <li>All uploads must be original performances. Any copyrighted material that is uploaded to the site will be removed and is grounds for account termination.</li>
        <li>All uploads must either be original compositions, or cover songs performed in such a way as to make it significantly different than the original.</li>
      </ul>
    </td>
  </tr>
  <tr>
    <td>
      <b>Voting on Battles</b>
    </td>
  </tr>
  <tr>
    <td>
      <ul>
        <li>You must be a registered member and currently logged on to the site in order to vote on a battle.</li>
        <li>You may only vote on a battle once.</li>
        <li>When voting on a battle, you must evaluate both competitor's compositions in all the specified categories.</li>
        <li>You may not vote on a battle that you are participating in.</li>
      </ul>
    </td>
  </tr>
  <tr>
    <td>
      <b>Recorded Materials</b>
    </td>
  </tr>
  <tr>
    <td>
      <ul>
        <li>Any recorded materials you upload to this site become property of <? print $sitename; ?> for the purposes of making such recordings available for download or for sale as part of a compilation. If your material is selected for such retransmission, the name of the author will accompany the transmission, however, the author will be due no royalties for such sales.</li>
        <li>While the above rule offers wide exposure that many artists will benefit from, <? print $sitename; ?> recognizes an artist's right to control the resale of his recorded material. If you wish to make a piece which you record exempt from future retransmissions, you may contact the maintainers of this site and request that your recordings not be used for such purposes. <? print $sitename; ?> will comply with all such requests.</li>
      </ul>
    </td>
  </tr>
</table>
