     <table cellpadding="0" cellspacing="0">
      <tr>
       <td width="700">
        <table width="700" cellpadding="2" cellspacing="0">
         <tr>
          <td class="item_title">Contact Us @ GuitarBattle.com</td>
         </tr>
         <tr>
          <td class="item">Your message has been sent. Thank you for your interest in GuitarBattle.com.</td>
         </tr>
        </table>
       </td>
      </tr>
     </table>
