     <table cellpadding="0" cellspacing="0">
      <tr>
       <td width="700">
        <table width="700" cellpadding="2" cellspacing="0">
         <tr>
          <td class="item_title">Notice:</td>
         </tr>
         <tr>
          <td class="item"><b class="alarm">There was an error in processing your request. Please go back and try again.</b></td>
         </tr>
        </table>
       </td>
      </tr>
     </table>
