<html>
 <head>
  <title>GuitarBattle.com</title>
  <link href="docs/style.css" rel="stylesheet" type="text/css">
 </head>
 <body topmargin="0" leftmargin="0" marginheight="0" marginwidth="0">
  <table cellpadding="0" cellspacing="0" align="center">
   <tr>
    <td width="700" height="100" align="right" valign="bottom" background="images/title.jpg">
<?php
	if($no_flash) {
?>
     <img src="images/top_menu_back.jpg"></td>
<?php
	}
	else {
?>
     <OBJECT classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=5,0,0,0" WIDTH=260 HEIGHT=64><PARAM NAME=movie VALUE="flash/menu.swf"><PARAM NAME=quality VALUE=high><PARAM NAME=bgcolor VALUE=#000000><EMBED src="flash/menu.swf" quality=high bgcolor=#000000 WIDTH=260 HEIGHT=64 TYPE="application/x-shockwave-flash" PLUGINSPAGE="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash"></EMBED></OBJECT></td>
<?php
	}
?>
   </tr>
   <tr>
    <td class="main">
