     <table cellpadding="0" cellspacing="0">
      <tr>
       <td width="700">
        <table width="700" cellpadding="2" cellspacing="0">
         <tr>
          <td class="item_title">Help:</td>
         </tr>
         <tr>
          <td class="large">GuitarBattle.com FAQ:</td>
         </tr>
         <tr>
          <td class="item"><b class="normal">Q:</b> What is GuitarBattle.com?</td>
         </tr>
         <tr>
          <td class="item"><b class="normal">A:</b> GuitarBattle.com is a website where guitarists and other musicians may meet and share their own music. The primary feature of GuitarBattle.com is the system of MP3 battles in which users may compete. All visitors of this website have the privilege of being able to observe all MP3 battles. If you are not already a member <a href="index.php?action=join" onMouseOver="window.status='Join GuitarBattle.com Now'; return true;" onMouseOut="window.status=''; return true;">Join</a> for FREE now!</td>
         </tr>
         <tr>
          <td class="item"><b class="normal">Q:</b> What should I do if I forget my password?</td>
         </tr>
         <tr>
          <td class="item"><b class="normal">A:</b> If you forget your password simply click on the <a href="index.php?location=forgotinfo" onMouseOver="window.status='Forgot your username and/or password?'; return true;" onMouseOut="window.status=''; return true;">Forgot your username and/or password?</a> link on the <a href="index.php" onMouseOver="window.status='Home'; return true;" onMouseOut="window.status=''; return true;">Home</a> page then enter the e-mail address that you registered your account under. After submitting this information your GuitarBattle.com username will be sent to your e-mail address along with a new, randomly generated password. Once you receive this e-mail you may log into the site and change your password using the "Change Your Password" link if you wish.</td>
         </tr>
         <tr>
          <td class="item"><b class="normal">Q:</b> How do I start a battle?</td>
         </tr>
         <tr>
          <td class="item"><b class="normal">A:</b> In order to start a battle you must first become a member. Please note that GuitarBattle.com membership is absolutely FREE. After your have become a member of GuitarBattle.com and you have logged into the site you may then click on the "Start a Battle" link from the Home page to create a battle. You must then select the battle category you wish to enter your battle into and you may then upload your MP3 file which must be no larger than 650kb.</td>
         </tr>
         <tr>
          <td class="item"><b class="normal">Q:</b> How do I join a battle?</td>
         </tr>
         <tr>
          <td class="item"><b class="normal">A:</b> In order to join a battle you must be a GuitarBattle.com member. After your have logged into the site you may then click on the "Join This Battle" link when viewing the battle you wish to join.</td>
         </tr>
         <tr>
          <td class="item"><b class="normal">Q:</b> How does a battle work once it has begun?</td>
         </tr>
         <tr>
          <td class="item"><b class="normal">A:</b> After you start a battle other members will be able to view your battle, listen to your MP3 file and post comments. After another user joins the battle, as the challenger, the battle will be active for 7 days. During the active period all GuitarBattle.com users will be able to vote on the battle. At the end of the 7 day active period the battle is closed and the winner is selected. All finished battles are then stored in The Vault.</td>
         </tr>
         <tr>
          <td class="item"><b class="normal">Q:</b> How do I view a battle that has ended?</td>
         </tr>
         <tr>
          <td class="item"><b class="normal">A:</b> In order to view finished battles that are stored in The Vault click on the "View Finished Battles" link from the Home page. All finished battles in this category will then be displayed and you may click on the individual battle links to view their information.</td>
         </tr>
         <tr><td class="item">&nbsp;</td></tr>
         <tr>
          <td class="item">Please <a href="index.php?location=contact" onMouseOver="window.status='Contact Us'; return true;" onMouseOut="window.status=''; return true;">Contact Us</a> if you have any other questions or suggestions.</td>
         </tr>
        </table>
       </td>
      </tr>
     </table>
