     <table cellpadding="0" cellspacing="0">
      <tr>
       <td width="700">
        <table width="700" cellpadding="2" cellspacing="0">
         <tr>
          <td class="item_title">Join this Battle:</td>
         </tr>
         <tr>
          <td class="item">Thank you for joining a battle at GuitarBattle.com. This battle is now active and open for voting, commenting and listening. All battles remain open for voting for 7 days. The winner is then selected after voting ends. Good luck and most of all, have fun.<br><br>Click here to <a href="battles.php?mode=view_battle&battle_id=<?php print("$battle_id"); ?>" onMouseOver="window.status='View Your Battle'; return true;" onMouseOut="window.status=''; return true;">View Your Battle</a>.</td>
         </tr>
        </table>
       </td>
      </tr>
     </table>
