     <table cellpadding="0" cellspacing="0">
      <tr>
       <td width="700">
        <table width="700" cellpadding="2" cellspacing="0">
         <tr>
          <td class="item_title" colspan="2">My GuitarBattle:</td>
         </tr>
         <tr>
          <td class="large" colspan="2"><?php print("$current_user"); ?></td>
         </tr>
         <tr>
          <td class="item" colspan="2">From this section, you can edit your profile, view your current battles, and set your preferences.</td>
         </tr>
         <tr><td class="item" colspan="2">&nbsp;</td></tr>
	 <tr><td class="item" colspan="2"><a href="index.php?mode=change_password">Change your password</a></td></tr>
	 <tr><td class="item" colspan="2"><a href="members.php?mode=edit_profile">Edit your profile</a></td></tr>
	 <tr><td class="item" colspan="2"><a href="">Battle history</a></td></tr>
        </table>
       </td>
      </tr>
     </table>
