     <table cellpadding="0" cellspacing="0">
      <tr>
       <td width="700">
        <table width="700" cellpadding="2" cellspacing="0">
         <tr>
          <td class="item_title">GuitarBattle.com Account Registration:</td>
         </tr>
         <tr>
          <td class="item">Your account registration has failed. Please <a href="index.php?action=join" onMouseOver="window.status='Join GuitarBattle.com Now'; return true;" onMouseOut="window.status=''; return true;">Go Back</a> and re-submit the registration form. Please make sure that you have entered a valid e-mail address.</td>
         </tr>
        </table>
       </td>
      </tr>
     </table>
