     <table cellpadding="0" cellspacing="0">
      <tr>
       <td width="700">
        <table width="700" cellpadding="2" cellspacing="0">
         <tr>
          <td class="item_title">GuitarBattle.com Account Registration:</td>
         </tr>
         <tr>
          <td class="item">Thank you for registering your account with GuitarBattle.com. You should receive your confirmation e-mail shortly. Please follow the link provided in your confirmation e-mail to activate your GuitarBattle.com account.</td>
         </tr>
        </table>
       </td>
      </tr>
     </table>
