     <table cellpadding="0" cellspacing="0">
      <tr>
       <td width="700">
        <table width="700" cellpadding="2" cellspacing="0">
         <tr>
          <td class="item_title">Start a Battle:</td>
         </tr>
         <tr>
          <td class="item">Thank you for starting a battle here at GuitarBattle.com. Your battle is now active and other users may join your battle, listen to your submission and post messages. Good luck and most of all, have fun.<br><br>Click here to <a href="battles.php?mode=view_battle&battle_id=<?php print("$battle_id"); ?>" onMouseOver="window.status='View Your Battle'; return true;" onMouseOut="window.status=''; return true;">View Your Battle</a></td>
         </tr>
        </table>
       </td>
      </tr>
     </table>
