     <table cellpadding="0" cellspacing="0">
      <tr>
       <td width="349" valign="top">
        <table width="349" cellpadding="2" cellspacing="0">
         <tr>
          <td class="item_title">TITLE GOES HERE:</td>
         </tr>
         <tr>
          <td class="item">INFO GOES HERE.</td>
         </tr>
        </table>
       </td>
       <td width="2" valign="top"><img src="images/2px_spacer.jpg"></td>
       <td width="349" valign="top">
<?php include('right_column.inc'); ?>
       </td>
      </tr>
     </table>
