     <table cellpadding="0" cellspacing="0">
      <tr>
       <td width="700">
        <table width="700" cellpadding="2" cellspacing="0">
         <tr>
          <td class="item_title">Under Construction:</td>
         </tr>
         <tr>
          <td class="item">Thank you for your interest in GuitarBattle.com.  Unfortunately, the website is still under construction.  Please check back shortly.</td>
         </tr>
        </table>
       </td>
      </tr>
     </table>
