     <table cellpadding="0" cellspacing="0">
      <tr>
       <td width="349" valign="top">
        <table width="349" cellpadding="2" cellspacing="0">
         <tr>
          <td class="item_title">GuitarBattle.com Utilities:</td>
         </tr>
         <tr>
          <td class="item"><b class="white">Winamp:</b> <a href="http://www.winamp.com" target="_blank">http://www.winamp.com</a></td>
         </tr>
        </table>
       </td>
       <td width="2" valign="top"><img src="images/2px_spacer.jpg"></td>
       <td width="349" valign="top">
<?php include('right_column.inc'); ?>
       </td>
      </tr>
     </table>
