<br><br>
<table width="350" border="0" class="items" cellspacing="0" cellpadding="4">
  <tr>
    <td class="item_title">
      Order Complete
    </td>
  </tr>
  <tr>
    <td align="center">
      Your order number is <b><? print zero_pad($HTTP_SESSION_VARS["compilation_id"], 6); ?></b>. Please write this down for future correspondence about your order. A confirmation e-mail has been sent to the e-mail address you provided. Production of your compilation disc will begin when payment is approved. Thank you for shopping at <? print $sitename; ?>!
    </td>
  </tr>
</table>
