                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr>
                      <td rowspan="3" style="background-image: url('images/news_frame_left.jpg'); font-size: 0px" width="20" height="198">
                        <img src="images/spacer.gif" border="0" alt="" width="20" height="198">
                      </td>
                      <td style="background-image: url('images/news_frame_top.jpg'); font-size: 0px" height="14">
                        <img src="images/spacer.gif" border="0" alt="" width="1" height="14">
                      </td>
                      <td rowspan="3" style="background-image: url('images/news_frame_right.jpg'); font-size: 0px" width="13" height="198">
                        <img src="images/spacer.gif" border="0" alt="" width="13" height="198">
                      </td>
                    </tr>
                    <tr valign="top">
                      <td height="170" style="background-color: #F1EDEE">
                        <img src="images/news_title.jpg" border="0" width="56" height="15" alt="News"><br>
                        <iframe src="include/templates/home/news.php" frameborder="0" width="100%" height="155"></iframe>
                      </td>
                    </tr>
                    <tr valign="top">
                      <td style="background-image: url('images/news_frame_bottom.jpg'); font-size: 0px" height="14">
                        <img src="images/spacer.gif" border="0" alt="" width="1" height="14">
                      </td>
                    </tr>
                  </table>
