<html>
<head>
<title>GuitarBattle Administration Site</title>
<link href="style.css" rel="stylesheet" type="text/css">
</head>
<body>

<table border="0" width="100%">
<tr>
<td align="center">

<table border="0" width="500">
<tr>
<td align="left">
<a href="http://www.guitarbattle.com"><img src="/images/title.jpg" border="0" alt="GuitarBattle.com"></a>
</td>
</tr>
<tr>
<td align="center">
<? include('navbar.inc'); ?><br><br>
</td>
</tr>
<tr>
<td align="center">

