<?
//General Site Settings
$sitename = "GuitarBattle.com";
$baseDir = "/home/rlarino/guitarbattle/htdocs/";
$baseURL = "http://www.guitarbattle.com";
$storeURL = "http://www.cafeshops.com/guitarbattle";
$domainName = "guitarbattle.com";
$myDomainName = "my.guitarbattle.com";
$styleSheet = "/include/style.css";
$webmaster_email = "webmaster@guitarbattle.com";
$info_email = "info@guitarbattle.com";
$copyright_email = "info@guitarbattle.com";
$bugs_email = "bugs@guitarbattle.com";
$sales_email = "sales@guitarbattle.com";
$advertising_email = "advertising@guitarbattle.com";
$irc_channel = "#guitarbattle";
$max_mp3_size = 716800;  // (bytes)
$max_simultaneous_battles = 2;
$min_vote = 1;
$max_vote = 5;
$battle_duration = 5; // (days)
$vote_bank_quota = 3; // # of battles a user must vote on before being able to post their own battle (first battle is an exception)
$user_icon_width = 300;
$user_icon_height = 150;
$temp_battle_life = 5; // # of hours before an entry gets deleted from the battles_temp table
$pending_account_life = 14; // # of days before a pending account request gets deleted
$compilation_life = 5;  // # of hours before an unfinished compilation should be deleted
$login_interval = 120; // number of minutes until an ip address can be reused to log into a different account
$max_compilation_length = 70; // maximum number of minutes a compilation cd can be
$compilation_cost = 10.00; // cost of a compilation cd (in dollars)
$domestic_shipping_rate = 4.00;
$international_shipping_rate = 10.00;
$tax_rate = 0.085;
$meta_keywords = "guitar battle, guitar, guitar competition, online competition, online guitar, Guitar Battle, GuitarBattle, guitarbattle, guitar community, guitar site";
$meta_description = "Online guitar competition and community for players of all skill ranges.";
?>
