<br><br>
<table border="0" cellspacing="5" cellpadding="0">
  <tr>
    <td>
      <table class="items" border="0" cellspacing="0" cellpadding="4">
        <tr>
          <td align="center">
            <a href="<? print $storeURL; ?>" border="0" target="_new"><img src="<? print $baseURL; ?>/images/gb_store.jpg" border="0" alt="GB Store"><br>
            <? print $sitename; ?> Apparel</a>
          </td>
        </tr>
      </table>
    </td>
    <td>
      <table class="items" border="0" cellspacing="0" cellpadding="4">
        <tr>
          <td align="center">
            <a href="<? print $baseURL; ?>/compilation/" border="0"><img src="<? print $baseURL; ?>/images/compilation_cd_small.gif" border="0" alt="Customer CD's"><br>
            Custom Compilation CD's</a>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
