<html>
 <head>
  <title><? print $sitename; ?> Administration Site</title>
  <link href="style.css" rel="stylesheet" type="text/css">
 </head>
 <body marginheight="0" marginwidth="0" topmargin="0" leftmargin="0">
  <table width="100%" border="0" cellpadding="4" cellspacing="0">
   <tr>
    <th colspan="2"><? print $sitename; ?> Administration Site</th>
   </tr>
   <tr>
    <td width="150" valign="top">
     <table class="item" width="150" border="0" cellpadding="4" cellspacing="0">
      <tr>
       <th align="left">Site Content</td>
      </tr>
      <tr>
       <td><a href="news.php">News</a></td>
      </tr>
      <tr>
       <td><a href="polls.php">Polls</a></td>
      </tr>
      <tr>
       <td><a href="links.php">Links</a></td>
      </tr>
      <tr>
       <td><a href="backings.php">Backings</a></td>
      </tr>
      <tr>
       <td><a href="">Advertisers</a></td>
      </tr>
      <tr>
      <tr>
       <th align="left">Users</td>
      </tr>
      <tr>
       <td><a href="listUsers.php">List Users</a></td>
      </tr>
      <tr>
       <td><a href="listUsers.php?mode=cancelUser">Cancel User</a></td>
      </tr>
      <tr>
       <td><a href="ranks.php">Ranks</a></td>
      </tr>
      <tr>
       <td><a href="judges.php">Judges</a></td>
      </tr>
      <tr>
       <th align="left">Battles</td>
      </tr>
      <tr>
       <td><a href="genres.php">Edit Genres</a></td>
      </tr>
      <tr>
       <td><a href="listBattles.php">List Battles</a></td>
      </tr>
      <tr>
       <td><a href="listBattles.php?mode=deleteBattle">Delete Battle</a></td>
      </tr>
      <tr>
       <td><a href="voting.php">Voting</a></td>
      </tr>
      <tr>
       <th align="left">Tools</td>
      </tr>
      <tr>
       <td><a href="massMessage.php">Mass Message</a></td>
      </tr>
      <tr>
       <td><a href="massMail.php">Mass Mail</a></td>
      </tr>
      <tr>
       <th align="left">Order Tracking</td>
      </tr>
      <tr>
       <td><a href="compilations.php">Compilations</a></td>
      </tr>
     </table><br>
     <a href="todo.php">To Do List</a>
    </td>
    <td valign="top">
